validation/src/main/java/gov/va/api/health/validation/api/ExactlyOneOf.java
validation/src/main/java/gov/va/api/health/validation/api/ZeroOrOneOf.java

Fix for unstable build.
Related story: https://vasdvp.atlassian.net/browse/API-1162

Task/api 1160 edit coverage eligibility response model for DARs

---

r4/src/main/java/gov/va/api/health/r4/api/information/WellKnown.java

Related Story: https://vasdvp.atlassian.net/browse/CER-29

added WellKnown class

---

r4/src/main/java/gov/va/api/health/r4/api/CoverageApi.java

Updated description to Coverage Eligibility Response.

Give better description to CER

---

r4/src/main/java/gov/va/api/health/r4/api/MetadataApi.java
r4/src/main/java/gov/va/api/health/r4/api/resources/Capability.java
r4/src/test/java/gov/va/api/health/r4/api/CapabilityTest.java
r4/src/test/java/gov/va/api/health/r4/api/samples/SampleCapabilities.java

Related Story: https://vasdvp.atlassian.net/browse/CER-21
Related Task: https://vasdvp.atlassian.net/browse/CER-43

added capability and metadata models to r4 resources

---

argonaut/pom.xml
dstu2/pom.xml
pom.xml
r4/pom.xml
r4/src/test/java/gov/va/api/health/r4/api/samples/SampleCapabilities.java
stu3/pom.xml
validation/pom.xml

https://vasdvp.atlassian.net/browse/APD-20
Revved parent pom to 2.0.7

revved all pom files

---

r4/src/main/java/gov/va/api/health/r4/api/resources/ExplanationOfBenefit.java
r4/src/test/java/gov/va/api/health/r4/api/resources/ExplanationOfBenefitsTest.java
r4/src/test/java/gov/va/api/health/r4/api/samples/SampleExplanationOfBenefits.java

Add R4 model and tests for ExplanationOfBenefit resource.
Resource: https://www.hl7.org/fhir/explanationofbenefit.html
Related task: https://vasdvp.atlassian.net/browse/API-1573

add ExplanationOfBenefit resource model and tests

---

dstu2/src/main/java/gov/va/api/health/dstu2/api/MetadataApi.java

https://vasdvp.atlassian.net/browse/ADQ-317
Me first, me first!

metadata doesnt use the oauth flow

---

r4/src/main/java/gov/va/api/health/r4/api/ClaimApi.java

Adding in reads of claims only for now.

Claim API for reads only

---

argonaut/pom.xml
dstu2/checkstyle-suppressions.xml
dstu2/pom.xml
pom.xml
r4/pom.xml
stu3/pom.xml
validation/pom.xml

https://vasdvp.atlassian.net/browse/SSS-44

SSS-44 dependency clean-up

---

r4/src/main/java/gov/va/api/health/r4/api/bundle/AbstractBundle.java
r4/src/main/java/gov/va/api/health/r4/api/resources/Claim.java
r4/src/main/java/gov/va/api/health/r4/api/resources/Coverage.java
r4/src/main/java/gov/va/api/health/r4/api/resources/CoverageEligibilityResponse.java

Update Claim with Entry and Bundle.  Also, found that the r4/AbstractBundle, total should be an Integer.  This change was made for consistency with other resources and the fhir spec.

Update Claim with Entry and Bundle and AbstractBundle total.

---

r4/src/main/java/gov/va/api/health/r4/api/ExplanationOfBenefitApi.java
r4/src/main/java/gov/va/api/health/r4/api/resources/ExplanationOfBenefit.java

Add explanation of benefit api

---

dstu2-examples/src/main/java/gov/va/api/health/dstu2/api/swaggerexamples/SwaggerOperationOutcome.java

https://vasdvp.atlassian.net/browse/SHANK-153
See also https://github.com/department-of-veterans-affairs/health-apis-data-query/pull/397

SHANK-153 - Generic OO Example

---

r4/src/main/java/gov/va/api/health/r4/api/resources/TerminologyCapabilities.java
r4/src/test/java/gov/va/api/health/r4/api/resources/TerminologyCapabilitiesTest.java
r4/src/test/java/gov/va/api/health/r4/api/samples/SampleTerminologyCapabilities.java

Add terminology capabilities

---

argonaut/src/main/java/gov/va/api/health/argonaut/api/AllergyIntoleranceApi.java
argonaut/src/main/java/gov/va/api/health/argonaut/api/ConditionApi.java
argonaut/src/main/java/gov/va/api/health/argonaut/api/DiagnosticReportApi.java
argonaut/src/main/java/gov/va/api/health/argonaut/api/ImmunizationApi.java
argonaut/src/main/java/gov/va/api/health/argonaut/api/MedicationApi.java
argonaut/src/main/java/gov/va/api/health/argonaut/api/MedicationOrderApi.java
argonaut/src/main/java/gov/va/api/health/argonaut/api/MedicationStatementApi.java
argonaut/src/main/java/gov/va/api/health/argonaut/api/ObservationApi.java
argonaut/src/main/java/gov/va/api/health/argonaut/api/PatientApi.java
argonaut/src/main/java/gov/va/api/health/argonaut/api/ProcedureApi.java
dstu2/src/main/java/gov/va/api/health/dstu2/api/AppointmentApi.java
dstu2/src/main/java/gov/va/api/health/dstu2/api/EncounterApi.java
dstu2/src/main/java/gov/va/api/health/dstu2/api/LocationApi.java
dstu2/src/main/java/gov/va/api/health/dstu2/api/MedicationDispenseApi.java
dstu2/src/main/java/gov/va/api/health/dstu2/api/OrganizationApi.java
dstu2/src/main/java/gov/va/api/health/dstu2/api/PractitionerApi.java

Story : https://vasdvp.atlassian.net/browse/SHANK-154
- added descriptions for existing parameters
- corrected incorrect parameters
- created a list of unlisted parameters as a comment in the story

add descriptions for all argonaut and dstu2 openAPI

---

stu3/src/main/java/gov/va/api/health/stu3/api/resources/Organization.java

https://vasdvp.atlassian.net/browse/SHANK-283

SHANK-283 Relax organization telecom requirement

---

stu3/src/main/java/gov/va/api/health/stu3/api/resources/Organization.java

https://vasdvp.atlassian.net/browse/SHANK-283

SHANK-283 Relax Argonaut required fields for Organization

---

stu3/src/main/java/gov/va/api/health/stu3/api/elements/Extension.java

https://vasdvp.atlassian.net/browse/SHANK-326

SHANK-326 Add missing valueId field to STU3 Extension

---

README.md
argonaut/README.md
dstu2/README.md
r4/README.md
stu3/README.md
us-core-r4-examples/src/main/java/gov/va/api/health/uscorer4/api/swaggerexamples/SwaggerCondition.java
us-core-r4/README.md
us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/ConditionApi.java
us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Condition.java
us-core-r4/src/test/java/gov/va/api/health/uscorer4/api/resources/ConditionTest.java
us-core-r4/src/test/java/gov/va/api/health/uscorer4/api/samples/SampleConditions.java
validation/README.md

https://vasdvp.atlassian.net/browse/SHANK-595

Shank 595 condition model

---

us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/AllergyIntolerance.java

https://vajira.max.gov/browse/API-558

API-891 Fix swagger example for AllergyIntolerance.Bundle

---

fhir-common/src/main/java/gov/va/api/health/fhir/api/FhirVersion.java
fhir-common/src/test/java/gov/va/api/health/fhir/api/FhirDateTimeTest.java
fhir-common/src/test/java/gov/va/api/health/fhir/api/FhirVersionTest.java

Adds FhirVersion enum to common lib

---

r4/src/main/java/gov/va/api/health/r4/api/datatypes/SampledData.java
us-core-r4-examples/src/main/java/gov/va/api/health/uscorer4/api/swaggerexamples/SwaggerObservation.java
us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/ObservationApi.java
us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Observation.java
us-core-r4/src/test/java/gov/va/api/health/uscorer4/api/resources/ObservationTest.java
us-core-r4/src/test/java/gov/va/api/health/uscorer4/api/samples/SampleDataTypes.java
us-core-r4/src/test/java/gov/va/api/health/uscorer4/api/samples/SampleKnownTypes.java
us-core-r4/src/test/java/gov/va/api/health/uscorer4/api/samples/SampleObservations.java

https://vajira.max.gov/browse/API-964
Labs: https://build.fhir.org/ig/HL7/US-Core-R4/StructureDefinition-us-core-observation-lab.html
Vital-Signs: http://hl7.org/fhir/R4/vitalsigns.html

Api 964 observation model

---

us-core-r4-examples/src/main/java/gov/va/api/health/uscorer4/api/swaggerexamples/SwaggerProcedure.java
us-core-r4/checkstyle-suppressions.xml
us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/ProcedureApi.java
us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Procedure.java
us-core-r4/src/test/java/gov/va/api/health/uscorer4/api/resources/ProcedureTest.java
us-core-r4/src/test/java/gov/va/api/health/uscorer4/api/samples/SampleProcedures.java

We are waiting on Feedback from the Data-Sources team reguarding `status` enums.

procedure model

---

argonaut-examples/src/main/java/gov/va/api/health/argonaut/api/swaggerexamples/SwaggerAllergyIntolerance.java
argonaut-examples/src/main/java/gov/va/api/health/argonaut/api/swaggerexamples/SwaggerCondition.java
argonaut-examples/src/main/java/gov/va/api/health/argonaut/api/swaggerexamples/SwaggerDiagnosticReport.java
argonaut-examples/src/main/java/gov/va/api/health/argonaut/api/swaggerexamples/SwaggerImmunization.java
argonaut-examples/src/main/java/gov/va/api/health/argonaut/api/swaggerexamples/SwaggerMedication.java
argonaut-examples/src/main/java/gov/va/api/health/argonaut/api/swaggerexamples/SwaggerMedicationOrder.java
argonaut-examples/src/main/java/gov/va/api/health/argonaut/api/swaggerexamples/SwaggerMedicationStatement.java
argonaut-examples/src/main/java/gov/va/api/health/argonaut/api/swaggerexamples/SwaggerObservation.java
argonaut-examples/src/main/java/gov/va/api/health/argonaut/api/swaggerexamples/SwaggerPatient.java
argonaut-examples/src/main/java/gov/va/api/health/argonaut/api/swaggerexamples/SwaggerProcedure.java
dstu2-examples/src/main/java/gov/va/api/health/dstu2/api/swaggerexamples/SwaggerAppointment.java
dstu2-examples/src/main/java/gov/va/api/health/dstu2/api/swaggerexamples/SwaggerEncounter.java
dstu2-examples/src/main/java/gov/va/api/health/dstu2/api/swaggerexamples/SwaggerLocation.java
dstu2-examples/src/main/java/gov/va/api/health/dstu2/api/swaggerexamples/SwaggerMedicationDispense.java
dstu2-examples/src/main/java/gov/va/api/health/dstu2/api/swaggerexamples/SwaggerOrganization.java
dstu2-examples/src/main/java/gov/va/api/health/dstu2/api/swaggerexamples/SwaggerPractitioner.java
r4-examples/src/main/java/gov/va/api/health/r4/api/swaggerexamples/SwaggerClaim.java
r4-examples/src/main/java/gov/va/api/health/r4/api/swaggerexamples/SwaggerCoverage.java
r4-examples/src/main/java/gov/va/api/health/r4/api/swaggerexamples/SwaggerCoverageEligibilityResponse.java
r4-examples/src/main/java/gov/va/api/health/r4/api/swaggerexamples/SwaggerExplanationOfBenefit.java

Replaced all dev-api references to sandbox-api

API-961-update-dev-to-sandbox-api-references

---

us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/ConditionApi.java

[API-1036](https://vajira.max.gov/browse/API-1036)
[R4 Observation Controller](https://github.com/department-of-veterans-affairs/health-apis-data-query/blob/master/data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/R4ConditionController.java)

API-1036-r4-condition-docs

---

us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/ObservationApi.java

[API-1037](https://vajira.max.gov/browse/API-1037)
[R4 Observation Controller](https://github.com/department-of-veterans-affairs/health-apis-data-query/blob/master/data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/R4ObservationController.java)

API-1037-r4-observation-openapi

---

us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/ProcedureApi.java

[VA Jira](https://vajira.max.gov/browse/API-1032)
[R4 Procedure Controller](https://github.com/department-of-veterans-affairs/health-apis-data-query/blob/master/data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/R4ProcedureController.java)

Update Procedure openapi for date search param

---

r4-examples/src/main/java/gov/va/api/health/r4/api/swaggerexamples/SwaggerCapabilityStatement.java
r4/src/main/java/gov/va/api/health/r4/api/ClaimApi.java
r4/src/main/java/gov/va/api/health/r4/api/CoverageApi.java
r4/src/main/java/gov/va/api/health/r4/api/CoverageEligibilityResponseApi.java
r4/src/main/java/gov/va/api/health/r4/api/ExplanationOfBenefitApi.java
r4/src/main/java/gov/va/api/health/r4/api/MetadataApi.java
stu3/src/main/java/gov/va/api/health/stu3/api/EndpointApi.java
stu3/src/main/java/gov/va/api/health/stu3/api/LocationApi.java
stu3/src/main/java/gov/va/api/health/stu3/api/MetadataApi.java
stu3/src/main/java/gov/va/api/health/stu3/api/OrganizationApi.java
stu3/src/main/java/gov/va/api/health/stu3/api/PractitionerApi.java
stu3/src/main/java/gov/va/api/health/stu3/api/PractitionerRoleApi.java

https://vajira.max.gov/browse/API-846

API-846 Remove json+fhir for stu3 and r4

---

Jenkinsfile
argonaut-examples/pom.xml
argonaut/pom.xml
dstu2-examples/pom.xml
dstu2/pom.xml
fhir-common/pom.xml
pom.xml
r4-examples/pom.xml
r4/pom.xml
stu3/pom.xml
us-core-r4-examples/pom.xml
us-core-r4/pom.xml
validation/pom.xml

https://vajira.max.gov/browse/API-1432

---

us-core-r4-examples/src/main/java/gov/va/api/health/uscorer4/api/swaggerexamples/SwaggerDiagnosticReport.java
us-core-r4/checkstyle-suppressions.xml
us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/DiagnosticReportApi.java
us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/DiagnosticReport.java
us-core-r4/src/test/java/gov/va/api/health/uscorer4/api/resources/DiagnosticReportTest.java
us-core-r4/src/test/java/gov/va/api/health/uscorer4/api/samples/SampleDiagnosticReports.java

[API-1572](https://vajira.max.gov/browse/API-1572)

Api 1572 diagnostic report r4 model

---

argonaut-examples/pom.xml
argonaut/pom.xml
dstu2-examples/pom.xml
dstu2/pom.xml
dstu2/src/main/java/gov/va/api/health/dstu2/api/bundle/AbstractBundle.java
dstu2/src/main/java/gov/va/api/health/dstu2/api/bundle/AbstractEntry.java
fhir-common/pom.xml
pom.xml
r4-examples/pom.xml
r4-examples/src/main/java/gov/va/api/health/r4/api/swaggerexamples/SwaggerCoverageEligibilityResponse.java
r4/pom.xml
r4/src/main/java/gov/va/api/health/r4/api/bundle/AbstractBundle.java
r4/src/main/java/gov/va/api/health/r4/api/bundle/AbstractEntry.java
stu3/pom.xml
stu3/src/main/java/gov/va/api/health/stu3/api/bundle/AbstractBundle.java
stu3/src/main/java/gov/va/api/health/stu3/api/bundle/AbstractEntry.java
us-core-r4-examples/pom.xml
us-core-r4/pom.xml
validation/pom.xml

https://vajira.max.gov/browse/API-1588

Api 1588 error prone fixes

---

us-core-r4-examples/src/main/java/gov/va/api/health/uscorer4/api/swaggerexamples/SwaggerLocation.java

[API-2081](https://vajira.max.gov/browse/API-2081)
[US Core R4 Location Profile](https://github.com/department-of-veterans-affairs/health-apis-fhir-resources/blob/master/us-core-r4/src/main/java/gov/va/api/health/uscorer4/api/resources/Location.java)

US Core R4 Location Swagger Examples

---

r4/src/main/java/gov/va/api/health/r4/api/resources/Appointment.java
r4/src/test/java/gov/va/api/health/r4/api/resources/AppointmentTest.java
r4/src/test/java/gov/va/api/health/r4/api/samples/SampleAppointments.java

Appointment, AppointmentTest, and SampleAppointments classes initialized

API-2320: R4 Appointment model

---

r4/src/main/java/gov/va/api/health/r4/api/resources/Claim.java

Set interface to DomainResource instead of Resource, set builder default for resourceType

R4 Claim model: set consistency to other models

---

pom.xml
us-core-r4-deidentifier/README.md
us-core-r4-deidentifier/pom.xml
us-core-r4-deidentifier/spotbugs-excludes.xml
us-core-r4-deidentifier/src/main/java/gov/va/api/health/uscorer4/PatientDeidentifier.java
us-core-r4-deidentifier/src/test/java/gov/va/api/health/uscorer4/PatientDeidentifierTest.java

Moved from [here](https://github.com/department-of-veterans-affairs/health-apis-bulk-fhir/blob/master/anonymizer/src/main/java/gov/va/api/health/bulkfhir/anonymizer/patient/PatientAnonymizer.java)

API-2355-patient-deidentification

---

us-core-r4-examples/src/main/java/gov/va/api/health/r4/api/swaggerexamples/SwaggerDevice.java
us-core-r4/src/main/java/gov/va/api/health/r4/api/DeviceApi.java
us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Device.java
us-core-r4/src/test/java/gov/va/api/health/r4/api/resources/DeviceTest.java
us-core-r4/src/test/java/gov/va/api/health/r4/api/samples/SampleDevices.java

Implemented Implantable Device FHIR resource:
http://hl7.org/fhir/us/core/StructureDefinition-us-core-implantable-device.html

Api 2899 r4 implantable device

---

us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Questionnaire.java
us-core-r4/src/test/java/gov/va/api/health/r4/api/resources/QuestionnaireTest.java
us-core-r4/src/test/java/gov/va/api/health/r4/api/samples/SampleQuestionnaires.java

https://vajira.max.gov/browse/API-3288

API-3288 R4 questionnaire

---

us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/QuestionnaireResponse.java
us-core-r4/src/test/java/gov/va/api/health/r4/api/resources/QuestionnaireResponseTest.java
us-core-r4/src/test/java/gov/va/api/health/r4/api/samples/SampleQuestionnaireResponses.java

Initial implementation of FHIR resource for QuestionnaireResponse.

questionnaireresponse

---

us-core-r4-examples/src/main/java/gov/va/api/health/r4/api/swaggerexamples/SwaggerQuestionnaire.java
us-core-r4-examples/src/main/java/gov/va/api/health/r4/api/swaggerexamples/SwaggerQuestionnaireResponse.java

This includes swagger examples for both API-3825 and API-3826

add swagger examples for Questionnaire and QuestionnaireResponse

---

pom.xml
test-support/pom.xml
test-support/spotbugs-excludes.xml
test-support/src/main/java/gov/va/api/health/fhir/testsupport/ResourceVerifier.java

API-5954-test-support-lib

---

.mvn/jvm.config
Jenkinsfile
argonaut-dstu2-examples/pom.xml
argonaut-dstu2/pom.xml
argonaut-stu3/pom.xml
deidentification-core/pom.xml
fhir-common/pom.xml
fhir-common/src/test/java/gov/va/api/health/fhir/api/FhirDateTimeParameterTest.java
pom.xml
test-support/pom.xml
us-core-r4-deidentifier/pom.xml
us-core-r4-examples/pom.xml
us-core-r4/pom.xml
us-core-r4/src/test/java/gov/va/api/health/r4/api/resources/AppointmentTest.java
us-core-r4/src/test/java/gov/va/api/health/r4/api/resources/DeviceTest.java
us-core-r4/src/test/java/gov/va/api/health/r4/api/resources/PractitionerRoleTest.java
us-core-r4/src/test/java/gov/va/api/health/r4/api/resources/QuestionnaireTest.java
us-core-r4/src/test/java/gov/va/api/health/r4/api/resources/RelatedPersonTest.java
validation/pom.xml

API-7444-java-16-upgrade

---

us-core-r4/src/main/java/gov/va/api/health/r4/api/AppointmentApi.java

https://vajira.max.gov/browse/API-7729

API-7729 appointment swagger

---

us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Organization.java

https://vajira.max.gov/browse/API-7607
After reviewing our model, and the data-mappings spreadsheet . it looks like we can build a compliant Organization from Vista.
Changes include fixing a broken link to the specification.

update links to documentation

---

argonaut-dstu2-examples/pom.xml
argonaut-dstu2/pom.xml
argonaut-stu3/pom.xml
argonaut-stu3/src/main/java/gov/va/api/health/stu3/api/datatypes/Address.java
argonaut-stu3/src/main/java/gov/va/api/health/stu3/api/datatypes/ContactPoint.java
argonaut-stu3/src/main/java/gov/va/api/health/stu3/api/datatypes/HumanName.java
argonaut-stu3/src/main/java/gov/va/api/health/stu3/api/datatypes/Identifier.java
argonaut-stu3/src/main/java/gov/va/api/health/stu3/api/datatypes/SampledData.java
argonaut-stu3/src/main/java/gov/va/api/health/stu3/api/resources/Endpoint.java
argonaut-stu3/src/main/java/gov/va/api/health/stu3/api/resources/Location.java
argonaut-stu3/src/main/java/gov/va/api/health/stu3/api/resources/Organization.java
argonaut-stu3/src/main/java/gov/va/api/health/stu3/api/resources/Practitioner.java
argonaut-stu3/src/main/java/gov/va/api/health/stu3/api/resources/PractitionerRole.java
argonaut-stu3/src/test/java/gov/va/api/health/stu3/api/samples/SampleDataTypes.java
argonaut-stu3/src/test/java/gov/va/api/health/stu3/api/samples/SampleLocations.java
argonaut-stu3/src/test/java/gov/va/api/health/stu3/api/samples/SampleOrganizations.java
argonaut-stu3/src/test/java/gov/va/api/health/stu3/api/samples/SamplePractitionerRoles.java
argonaut-stu3/src/test/java/gov/va/api/health/stu3/api/samples/SamplePractitioners.java
deidentification-core/pom.xml
fhir-common/pom.xml
pom.xml
test-support/pom.xml
us-core-r4-deidentifier/pom.xml
us-core-r4-examples/pom.xml
us-core-r4/pom.xml
validation/pom.xml

Some STU3 integration tests are failing on DQ due to a schema validation error. Need to update this schema to match the base STU3 spec before IT failures can be addressed.
DQ PR: https://github.com/department-of-veterans-affairs/health-apis-data-query/pull/755

API-7988: STU3 model discrepancies

---

us-core-r4/src/main/java/gov/va/api/health/r4/api/PractitionerApi.java
us-core-r4/src/main/java/gov/va/api/health/r4/api/PractitionerRoleApi.java

Adds `practitioner.identifier` and `practitioner.name` to R4 PractitionerRole.

API-3701: Add new search params to PractitionerRole

---

us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/Organization.java

https://www.hl7.org/fhir/organization.html
https://build.fhir.org/ig/HL7/carin-bb/StructureDefinition-C4BB-Organization.html

make contact a list per the spec

---

us-core-r4-examples/src/main/java/gov/va/api/health/r4/api/swaggerexamples/SwaggerMedicationDispense.java
us-core-r4/src/main/java/gov/va/api/health/r4/api/resources/MedicationDispense.java
us-core-r4/src/test/java/gov/va/api/health/r4/api/resources/MedicationDispenseTest.java
us-core-r4/src/test/java/gov/va/api/health/r4/api/samples/SampleMedicationDispenses.java

Lasershark team adding MedicationDispense Resource as per FHIR guidelines. Please let us know if there are any issues!
GH Issue: https://github.com/department-of-veterans-affairs/lasershark/issues/73

Add MedicationDispense Resource
